name: literacy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6
  google_fonts: ^1.1.1
  awesome_dialog: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/loginLogo.png
    - assets/images/numbers/numberZero.png
    - assets/images/numbers/numberOne.png
    - assets/images/numbers/numberTwo.png
    - assets/images/numbers/numberThree.png
    - assets/images/numbers/numberFour.png
    - assets/images/numbers/numberFive.png
    - assets/images/numbers/numberSix.png
    - assets/images/numbers/numberSeven.png
    - assets/images/numbers/numberEight.png
    - assets/images/numbers/numberNine.png
    - assets/images/letters/letterA.png
    - assets/images/letters/letterB.png
    - assets/images/letters/letterC.png
    - assets/images/letters/letterD.png
    - assets/images/letters/letterE.png
    - assets/images/letters/letterF.png
    - assets/images/letters/letterG.png
    - assets/images/letters/letterH.png
    - assets/images/letters/letterI.png
    - assets/images/letters/letterJ.png
    - assets/images/letters/letterK.png
    - assets/images/letters/letterL.png
    - assets/images/letters/letterM.png
    - assets/images/letters/letterN.png
    - assets/images/letters/letterO.png
    - assets/images/letters/letterP.png
    - assets/images/letters/letterQ.png
    - assets/images/letters/letterR.png
    - assets/images/letters/letterS.png
    - assets/images/letters/letterT.png
    - assets/images/letters/letterU.png
    - assets/images/letters/letterV.png
    - assets/images/letters/letterW.png
    - assets/images/letters/letterX.png
    - assets/images/letters/letterY.png
    - assets/images/letters/letterZ.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
